package ihm;

public class PGPanelExplorer extends javax.swing.JPanel {

    /**
     * Creates new form PGPanelExplorer
     */
    public PGPanelExplorer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pGPanelListN = new  PGPanelListN();
        pGPanelListA = new  PGPanelListA();
        pGPanelListO = new  PGPanelListO();

        setBackground(new java.awt.Color(68, 71, 93));

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addTab("Noeud", pGPanelListN);
        jTabbedPane1.addTab("Arrêtes", pGPanelListA);
        jTabbedPane1.addTab("Objectifs",  pGPanelListO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("List Noeud");
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JTabbedPane jTabbedPane1;
    private  PGPanelListA pGPanelListA;
    private  PGPanelListN pGPanelListN;
    private  PGPanelListO pGPanelListO;
    // End of variables declaration                   
}