package ihm;

public class PGPanelListA extends javax.swing.JPanel {

    /**
     * Creates new form PGPanelListA
     */
    public PGPanelListA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblNoeudA = new javax.swing.JLabel();
        lblNoeudB = new javax.swing.JLabel();
        lbl2Sens = new javax.swing.JLabel();
        lblCouleurAB = new javax.swing.JLabel();
        lblDistance = new javax.swing.JLabel();
        lblCouleurBA = new javax.swing.JLabel();
        comboBoxListNoeudA = new javax.swing.JComboBox<>();
        comboBoxListNoeudB = new javax.swing.JComboBox<>();
        cb2Sens = new javax.swing.JCheckBox();
        txtDistance = new javax.swing.JTextField();
        btnCouleurAB = new javax.swing.JButton();
        btnCouleurBA = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();

        setBackground(new java.awt.Color(68, 71, 90));
        setForeground(new java.awt.Color(255, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        lblNoeudA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNoeudA.setForeground(new java.awt.Color(255, 255, 255));
        lblNoeudA.setText("Noeud A");

        lblNoeudB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNoeudB.setForeground(new java.awt.Color(255, 255, 255));
        lblNoeudB.setText("Noeud B");

        lbl2Sens.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl2Sens.setForeground(new java.awt.Color(255, 255, 255));
        lbl2Sens.setText("2 sens");

        lblCouleurAB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCouleurAB.setForeground(new java.awt.Color(255, 255, 255));
        lblCouleurAB.setText("Couleur AB");

        lblDistance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDistance.setForeground(new java.awt.Color(255, 255, 255));
        lblDistance.setText("Distance");

        lblCouleurBA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCouleurBA.setForeground(new java.awt.Color(255, 255, 255));
        lblCouleurBA.setText("Couleur BA");

        comboBoxListNoeudA.setBackground(new java.awt.Color(40, 42, 54));
        comboBoxListNoeudA.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxListNoeudA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxListNoeudA.setBorder(null);
        comboBoxListNoeudA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxListNoeudAActionPerformed(evt);
            }
        });

        comboBoxListNoeudB.setBackground(new java.awt.Color(40, 42, 54));
        comboBoxListNoeudB.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxListNoeudB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxListNoeudB.setBorder(null);
        comboBoxListNoeudB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxListNoeudBActionPerformed(evt);
            }
        });

        cb2Sens.setBackground(new java.awt.Color(68, 71, 90));
        cb2Sens.setSelected(true);
        cb2Sens.setBorder(null);
        cb2Sens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2SensActionPerformed(evt);
            }
        });

        txtDistance.setBackground(new java.awt.Color(40, 42, 54));
        txtDistance.setForeground(new java.awt.Color(255, 255, 255));
        txtDistance.setBorder(null);
        txtDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanceActionPerformed(evt);
            }
        });
        btnCouleurAB.setFocusPainted(false);
        btnCouleurAB.setText(" ");
        btnCouleurAB.setBorder(null);
        btnCouleurAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCouleurABActionPerformed(evt);
            }
        });
        btnCouleurBA.setFocusPainted(false);
        btnCouleurBA.setText(" ");
        btnCouleurBA.setBorder(null);
        btnCouleurBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCouleurBAActionPerformed(evt);
            }
        });
        btnAjouter.setFocusPainted(false);
        btnAjouter.setBackground(new java.awt.Color(40, 42, 54));
        btnAjouter.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter.setText("Ajouter");
        btnAjouter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        btnSupprimer.setFocusPainted(false);
        btnSupprimer.setBackground(new java.awt.Color(40, 42, 54));
        btnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimer.setText("Supprimer");
        btnSupprimer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2Sens)
                        .addGap(47, 47, 47)
                        .addComponent(cb2Sens))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNoeudA)
                            .addGap(32, 32, 32)
                            .addComponent(comboBoxListNoeudA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNoeudB)
                            .addGap(33, 33, 33)
                            .addComponent(comboBoxListNoeudB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDistance)
                        .addGap(34, 34, 34)
                        .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCouleurBA)
                            .addGap(18, 18, 18)
                            .addComponent(btnCouleurBA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCouleurAB)
                            .addGap(18, 18, 18)
                            .addComponent(btnCouleurAB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNoeudA)
                            .addComponent(comboBoxListNoeudA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDistance)
                            .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNoeudB)
                            .addComponent(comboBoxListNoeudB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCouleurAB)
                            .addComponent(btnCouleurAB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl2Sens)
                                .addComponent(cb2Sens, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCouleurBA))
                            .addComponent(btnCouleurBA)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

                       

    private void cb2SensActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnCouleurBAActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnCouleurABActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtDistanceActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void comboBoxListNoeudBActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void comboBoxListNoeudAActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnCouleurAB;
    private javax.swing.JButton btnCouleurBA;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JCheckBox cb2Sens;
    private javax.swing.JComboBox<String> comboBoxListNoeudA;
    private javax.swing.JComboBox<String> comboBoxListNoeudB;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl2Sens;
    private javax.swing.JLabel lblCouleurAB;
    private javax.swing.JLabel lblCouleurBA;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblNoeudA;
    private javax.swing.JLabel lblNoeudB;
    private javax.swing.JTextField txtDistance;
    // End of variables declaration                   
}